/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.mikroskil.elm_skripsi;

import com.mikroskil.elm_skripsi.Learning.LearningPage;
import com.mikroskil.elm_skripsi.Learning.Predict;
import com.mikroskil.elm_skripsi.Learning.TestingPage;
import com.mikroskil.elm_skripsi.Library.Inverse;
import com.mikroskil.elm_skripsi.appendWizard.DataAppendFinishPage;
import com.mikroskil.elm_skripsi.appendWizard.DataAppendPage;
import com.mikroskil.elm_skripsi.delete.DeleteDialog;
import com.mikroskil.elm_skripsi.importWizard.EMACounterPage;
import com.mikroskil.elm_skripsi.importWizard.DataNormalizationPage;
import com.mikroskil.elm_skripsi.importWizard.FileSelectionPage;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import com.mikroskil.elm_skripsi.wizard.*;
import javax.swing.JFrame;

/**
 *
 * @author Andy Wijaya
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form LearningAndTesting
     */
    public Main() {
        initComponents();
//        double[][] values = new double[][]{
//            {0.29,0.32,0.16,0.52,0.74,0.11},
//            {0.04,0.11,0.35,0.80,0.48,0.53}
//        };
//        double[][] temp_trans = new double[][]{
//            {0.991,0.952,0.952,0.975,0.993,0.994},
//            {0.991,1.000,1.000,0.983,1.000,1.000}
//        };
//        DenseMatrix A = new DenseMatrix(values);
//        DenseMatrix B = new DenseMatrix(temp_trans);
//        DenseMatrix C = new DenseMatrix(2,2);
//        A.mult(B, C);
//        for(int i=0;i<C.numRows();i++){
//            for(int j=0;j<C.numColumns();j++){
//                System.out.print(C.get(i, j)+" ");
//            }
//            System.out.println();
//        }
////        DenseMatrix transT = new DenseMatrix(temp_trans);
////        DenseMatrix temp = new DenseMatrix(values);
////        Inverse inverse = new Inverse(temp);
////        try {
////            DenseMatrix result = inverse.getMPInverse();
////            for(int i=0;i<result.numRows();i++){
////                for(int j=0;j<result.numColumns();j++){
////                    System.out.print(result.get(i, j)+" ");
////                }
////                System.out.println();
////            }
////            DenseMatrix outputWeight = new DenseMatrix(2,1);
////            result.mult(transT,outputWeight);
////            for(int i=0;i<outputWeight.numRows();i++){
////                for(int j=0;j<outputWeight.numColumns();j++){
////                    System.out.print(outputWeight.get(i, j)+" ");
////                }
////                System.out.println();
////            }
////            
////        } catch (NotConvergedException ex) {
////           //Logger.getLogger(com.mikroskil.elm_skripsi.Library.Main.class.getName()).log(Level.SEVERE, null, ex);
////        }
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuImportData = new javax.swing.JMenuItem();
        mnuAppendData = new javax.swing.JMenuItem();
        mnuDeleteData = new javax.swing.JMenuItem();
        mnuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuTesting = new javax.swing.JMenuItem();
        menuPrediksi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenu1.setText("File");

        mnuImportData.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuImportData.setText("Import Data");
        mnuImportData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuImportDataActionPerformed(evt);
            }
        });
        jMenu1.add(mnuImportData);

        mnuAppendData.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuAppendData.setText("Append Data");
        mnuAppendData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAppendDataActionPerformed(evt);
            }
        });
        jMenu1.add(mnuAppendData);

        mnuDeleteData.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuDeleteData.setText("Delete Data");
        mnuDeleteData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDeleteDataActionPerformed(evt);
            }
        });
        jMenu1.add(mnuDeleteData);

        mnuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Proses");

        jMenuItem1.setText("Training");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        mnuTesting.setText("Testing");
        mnuTesting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTestingActionPerformed(evt);
            }
        });
        jMenu2.add(mnuTesting);

        menuPrediksi.setText("Prediksi");
        menuPrediksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPrediksiActionPerformed(evt);
            }
        });
        jMenu2.add(menuPrediksi);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuImportDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuImportDataActionPerformed
        WizardAction wa = new WizardAction(this);
        wa.add(new FileSelectionPage(wa,"Pilih File"));
        wa.add(new EMACounterPage(wa,"Perhitungan EMA"));
        wa.add(new DataNormalizationPage(wa,"Penyelesaian Import Data"));
        wa.show();
    }//GEN-LAST:event_mnuImportDataActionPerformed

    private void mnuAppendDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAppendDataActionPerformed
        WizardAction wa = new WizardAction(this);
        wa.add(new DataAppendPage(wa,"Pilih File"));
        wa.add(new DataAppendFinishPage(wa,"Penyelesaian Append Data"));
        wa.show();
    }//GEN-LAST:event_mnuAppendDataActionPerformed

    private void mnuDeleteDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDeleteDataActionPerformed
        DeleteDialog dd = new DeleteDialog(this, true);
        dd.show();
    }//GEN-LAST:event_mnuDeleteDataActionPerformed

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_mnuExitActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        LearningPage  main = new LearningPage(this,true);
        main.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mnuTestingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTestingActionPerformed
        TestingPage main = new TestingPage(this, true);
        main.show();
    }//GEN-LAST:event_mnuTestingActionPerformed

    private void menuPrediksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPrediksiActionPerformed
        Predict main = new Predict(this,true);
        main.show();
    }//GEN-LAST:event_menuPrediksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuPrediksi;
    private javax.swing.JMenuItem mnuAppendData;
    private javax.swing.JMenuItem mnuDeleteData;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenuItem mnuImportData;
    private javax.swing.JMenuItem mnuTesting;
    // End of variables declaration//GEN-END:variables
}
