/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.mikroskil.elm_skripsi.Learning;

import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.table.TableModel;

/**
 *
 * @author Andy Wijaya
 */
public class LearningAndTesting extends javax.swing.JDialog {
    
    private LearningAndTestingAction pageAction;
    /**
     * Creates new form Main
     */
    public LearningAndTesting(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        pageAction = new LearningAndTestingAction(this);
        pageAction.initialize();
    }
    
    public void fillKodeSaham(ComboBoxModel model){
        cmbKodeSaham.setModel(model);
    }
    
    public void fillTahunAwalTrain(ComboBoxModel model){
        cmbTahunTrainAwal.setModel(model);
    }
    
    public void fillTahunAkhirTrain(ComboBoxModel model){
        cmbTahunTrainAkhir.setModel(model);
    }
    
    public void fillTahunAwalTest(ComboBoxModel model){
        cmbTahunTestAwal.setModel(model);
    }
    
    public void fillTahunAkhirTest(ComboBoxModel model){
        cmbTahunTestAkhir.setModel(model);
    }
    
    public void fillBulanAwalTrain(ComboBoxModel model){
        cmbBulanTrainAwal.setModel(model);
    }
    
    public void fillBulanAkhirTrain(ComboBoxModel model){
        cmbBulanTrainAkhir.setModel(model);
    }
    
    public void fillBulanAwalTest(ComboBoxModel model){
        cmbBulanTestAwal.setModel(model);
    }
    
    public void fillBulanAkhirTest(ComboBoxModel model){
        cmbBulanTestAkhir.setModel(model);
    }
    
    public void fillResultTable(TableModel model){
        tblMain.setModel(model);
    }
    
    public void setAccuracy(double accuracy){
        lblAkurasi.setText(String.format("%.2f%%",accuracy));
    }
    
    public void setPresisiAndRecall(double presisiNaik, double presisiTetap, double presisiTurun, double recallNaik, double recallTetap, double recallTurun){
        lblPresisiNaik.setText(String.format("%.2f%%",presisiNaik));
        lblPresisiTetap.setText(String.format("%.2f%%",presisiTetap));
        lblPresisiTurun.setText(String.format("%.2f%%", presisiTurun));
        lblRecallNaik.setText(String.format("%.2f%%", recallNaik));
        lblRecallTetap.setText(String.format("%.2f%%",recallTetap));
        lblRecallTurun.setText(String.format("%.2f%%", recallTurun));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbKodeSaham = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbTahunTrainAwal = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cmbTahunTrainAkhir = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cmbBulanTrainAwal = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cmbBulanTrainAkhir = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmbTahunTestAwal = new javax.swing.JComboBox();
        cmbTahunTestAkhir = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        cmbBulanTestAwal = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        cmbBulanTestAkhir = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMain = new javax.swing.JTable();
        btnProcess = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblPresisiNaik = new javax.swing.JLabel();
        lblPresisiTetap = new javax.swing.JLabel();
        lblPresisiTurun = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblRecallNaik = new javax.swing.JLabel();
        lblRecallTetap = new javax.swing.JLabel();
        lblRecallTurun = new javax.swing.JLabel();
        Akurasi = new javax.swing.JLabel();
        lblAkurasi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(535, 409));

        jLabel1.setText("Kode Saham");

        cmbKodeSaham.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbKodeSahamItemStateChanged(evt);
            }
        });

        jLabel2.setText("Training Set : ");

        jLabel3.setText("Tahun");

        cmbTahunTrainAwal.setEnabled(false);
        cmbTahunTrainAwal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTahunTrainAwalItemStateChanged(evt);
            }
        });

        jLabel4.setText("-");

        cmbTahunTrainAkhir.setEnabled(false);
        cmbTahunTrainAkhir.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTahunTrainAkhirItemStateChanged(evt);
            }
        });

        jLabel5.setText("Bulan");

        cmbBulanTrainAwal.setEnabled(false);
        cmbBulanTrainAwal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbBulanTrainAwalItemStateChanged(evt);
            }
        });

        jLabel6.setText("-");

        cmbBulanTrainAkhir.setEnabled(false);
        cmbBulanTrainAkhir.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbBulanTrainAkhirItemStateChanged(evt);
            }
        });

        jLabel7.setText("Testing Set :");

        jLabel8.setText("Tahun");

        jLabel9.setText("Bulan");

        cmbTahunTestAwal.setEnabled(false);
        cmbTahunTestAwal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTahunTestAwalItemStateChanged(evt);
            }
        });

        cmbTahunTestAkhir.setEnabled(false);
        cmbTahunTestAkhir.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTahunTestAkhirItemStateChanged(evt);
            }
        });

        jLabel10.setText("-");

        cmbBulanTestAwal.setEnabled(false);
        cmbBulanTestAwal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbBulanTestAwalItemStateChanged(evt);
            }
        });

        jLabel11.setText("-");

        cmbBulanTestAkhir.setEnabled(false);
        cmbBulanTestAkhir.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbBulanTestAkhirItemStateChanged(evt);
            }
        });

        tblMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tanggal", "Hasil Prediksi", "Kenyataan"
            }
        ));
        jScrollPane1.setViewportView(tblMain);

        btnProcess.setText("Process");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));

        jLabel12.setText("Presisi Naik");

        jLabel13.setText("Presisi Tetap");

        jLabel14.setText("Presisi Turun");

        lblPresisiNaik.setText("0%");

        lblPresisiTetap.setText("0%");

        lblPresisiTurun.setText("0%");

        jLabel18.setText("Recall Naik");

        jLabel19.setText("Recall Tetap");

        jLabel20.setText("Recall Turun");

        lblRecallNaik.setText("0%");

        lblRecallTetap.setText("0%");

        lblRecallTurun.setText("0%");

        Akurasi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Akurasi.setText("Akurasi     :");

        lblAkurasi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAkurasi.setText("0%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPresisiTurun))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPresisiTetap))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(41, 41, 41)
                                .addComponent(lblPresisiNaik)))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRecallNaik)
                            .addComponent(lblRecallTetap)
                            .addComponent(lblRecallTurun)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Akurasi)
                        .addGap(34, 34, 34)
                        .addComponent(lblAkurasi)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Akurasi)
                    .addComponent(lblAkurasi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblPresisiNaik)
                    .addComponent(jLabel18)
                    .addComponent(lblRecallNaik))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblPresisiTetap)
                    .addComponent(jLabel19)
                    .addComponent(lblRecallTetap))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblPresisiTurun)
                    .addComponent(jLabel20)
                    .addComponent(lblRecallTurun))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnProcess)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbTahunTrainAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbTahunTrainAkhir, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(70, 70, 70)
                                .addComponent(cmbKodeSaham, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbBulanTrainAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbBulanTrainAkhir, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbTahunTestAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbTahunTestAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbBulanTestAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbBulanTestAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbKodeSaham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTahunTrainAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cmbTahunTrainAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTahunTestAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cmbTahunTestAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBulanTrainAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cmbBulanTrainAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBulanTestAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(cmbBulanTestAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnProcess)
                            .addComponent(btnCancel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbKodeSahamItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbKodeSahamItemStateChanged
        pageAction.setChoosen((String)evt.getItem());
    }//GEN-LAST:event_cmbKodeSahamItemStateChanged

    private void cmbTahunTrainAwalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTahunTrainAwalItemStateChanged
        pageAction.setEndYearTrain((String)evt.getItem());
    }//GEN-LAST:event_cmbTahunTrainAwalItemStateChanged

    private void cmbTahunTrainAkhirItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTahunTrainAkhirItemStateChanged
        pageAction.setStartYearTest((String)evt.getItem());
    }//GEN-LAST:event_cmbTahunTrainAkhirItemStateChanged

    private void cmbTahunTestAwalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTahunTestAwalItemStateChanged
        pageAction.setEndYearTest((String)evt.getItem());
    }//GEN-LAST:event_cmbTahunTestAwalItemStateChanged

    private void cmbTahunTestAkhirItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTahunTestAkhirItemStateChanged
        pageAction.setEndYear((String)evt.getItem());
    }//GEN-LAST:event_cmbTahunTestAkhirItemStateChanged

    private void cmbBulanTrainAwalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbBulanTrainAwalItemStateChanged
        pageAction.setEndMonthTrain((String)evt.getItem());
    }//GEN-LAST:event_cmbBulanTrainAwalItemStateChanged

    private void cmbBulanTrainAkhirItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbBulanTrainAkhirItemStateChanged
        pageAction.setStartMonthTest((String)evt.getItem());
    }//GEN-LAST:event_cmbBulanTrainAkhirItemStateChanged

    private void cmbBulanTestAwalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbBulanTestAwalItemStateChanged
        pageAction.setEndMonthTest((String)evt.getItem());
    }//GEN-LAST:event_cmbBulanTestAwalItemStateChanged

    private void cmbBulanTestAkhirItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbBulanTestAkhirItemStateChanged
        pageAction.setEndMonth((String)evt.getItem());
    }//GEN-LAST:event_cmbBulanTestAkhirItemStateChanged

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        pageAction.doLearningAndTesting();
    }//GEN-LAST:event_btnProcessActionPerformed
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LearningAndTesting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LearningAndTesting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LearningAndTesting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LearningAndTesting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LearningAndTesting dialog = new LearningAndTesting(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Akurasi;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnProcess;
    private javax.swing.JComboBox cmbBulanTestAkhir;
    private javax.swing.JComboBox cmbBulanTestAwal;
    private javax.swing.JComboBox cmbBulanTrainAkhir;
    private javax.swing.JComboBox cmbBulanTrainAwal;
    private javax.swing.JComboBox cmbKodeSaham;
    private javax.swing.JComboBox cmbTahunTestAkhir;
    private javax.swing.JComboBox cmbTahunTestAwal;
    private javax.swing.JComboBox cmbTahunTrainAkhir;
    private javax.swing.JComboBox cmbTahunTrainAwal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAkurasi;
    private javax.swing.JLabel lblPresisiNaik;
    private javax.swing.JLabel lblPresisiTetap;
    private javax.swing.JLabel lblPresisiTurun;
    private javax.swing.JLabel lblRecallNaik;
    private javax.swing.JLabel lblRecallTetap;
    private javax.swing.JLabel lblRecallTurun;
    private javax.swing.JTable tblMain;
    // End of variables declaration//GEN-END:variables
    
    public JComboBox getCmbTahunTrainAwal(){
        return cmbTahunTrainAwal;
    }
    
    public JComboBox getCmbTahunTrainAkhir(){
        return cmbTahunTrainAkhir;
    }
    
    public JComboBox getCmbTahunTestAwal(){
        return cmbTahunTestAwal;
    }
    
    public JComboBox getCmbTahunTestAkhir(){
        return cmbTahunTestAkhir;
    }
    
    public JComboBox getCmbBulanTrainAwal(){
        return cmbBulanTrainAwal;
    }
    
    public JComboBox getCmbBulanTrainAkhir(){
        return cmbBulanTrainAkhir;
    }
    
    public JComboBox getCmbBulanTestAwal(){
        return cmbBulanTestAwal;
    }
    
    public JComboBox getCmbBulanTestAkhir(){
        return cmbBulanTestAkhir;
    }
}
