/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.mikroskil.elm_skripsi.importWizard;
import com.mikroskil.elm_skripsi.model.Share;
import com.mikroskil.elm_skripsi.wizard.WizardAction;
import com.mikroskil.elm_skripsi.wizard.WizardPage;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableModel;

/**
 *
 * @author Andy Wijaya
 */
public class EMACounterPage extends WizardPage{
    
    /**
     * Creates new form EMACounterPage
     */
    public EMACounterPage() {
        pageAction = new EMACounterAction(this);
        initComponents();
    }
    
    public EMACounterPage(WizardAction wizardAction,String title){
        super(wizardAction, title);
        pageAction = new EMACounterAction(this);
        initComponents();
    }
    
    public void setTableModel(TableModel tableModel){
        mainTable.setModel(tableModel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrice = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTertinggi = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblOpenHighest = new javax.swing.JLabel();
        lblCloseHighest = new javax.swing.JLabel();
        lblHighHighest = new javax.swing.JLabel();
        lblLowHighest = new javax.swing.JLabel();
        lblOpenLowest = new javax.swing.JLabel();
        lblCloseLowest = new javax.swing.JLabel();
        lblHighLowest = new javax.swing.JLabel();
        lblLowLowest = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblKode = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblNamaSaham = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblJumlahData = new javax.swing.JLabel();
        lblAwalData = new javax.swing.JLabel();
        lblAkhirData = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 245, 245));

        pnlPrice.setBackground(new java.awt.Color(102, 255, 102));
        pnlPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Open");

        lblTertinggi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTertinggi.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTertinggi.setText("Tertinggi");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Terendah");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Close");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("High");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Low");

        lblOpenHighest.setText("jLabel6");

        lblCloseHighest.setText("jLabel7");

        lblHighHighest.setText("jLabel8");

        lblLowHighest.setText("jLabel9");

        lblOpenLowest.setText("jLabel10");

        lblCloseLowest.setText("jLabel11");

        lblHighLowest.setText("jLabel12");

        lblLowLowest.setText("jLabel14");

        javax.swing.GroupLayout pnlPriceLayout = new javax.swing.GroupLayout(pnlPrice);
        pnlPrice.setLayout(pnlPriceLayout);
        pnlPriceLayout.setHorizontalGroup(
            pnlPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPriceLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(65, 65, 65)
                .addGroup(pnlPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTertinggi)
                    .addComponent(lblOpenHighest)
                    .addComponent(lblCloseHighest)
                    .addComponent(lblHighHighest)
                    .addComponent(lblLowHighest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(pnlPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lblOpenLowest)
                    .addComponent(lblCloseLowest)
                    .addComponent(lblHighLowest)
                    .addComponent(lblLowLowest))
                .addGap(33, 33, 33))
        );
        pnlPriceLayout.setVerticalGroup(
            pnlPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPriceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTertinggi)
                    .addComponent(jLabel3))
                .addGap(8, 8, 8)
                .addGroup(pnlPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblOpenHighest)
                    .addComponent(lblOpenLowest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblCloseHighest)
                    .addComponent(lblCloseLowest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblHighHighest)
                    .addComponent(lblHighLowest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblLowHighest)
                    .addComponent(lblLowLowest))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setText("Kode Saham");

        lblKode.setText("KODE");

        jLabel7.setText("Nama Saham");

        lblNamaSaham.setText("Nama");

        jLabel9.setText("Jumlah Data");

        jLabel10.setText("Awal Data");

        jLabel11.setText("Akhir Data");

        lblJumlahData.setText("X Records");

        lblAwalData.setText("DD/MM/YYYY");

        lblAkhirData.setText("DD/MM/YYYY");

        lblMessage.setText("Hasil Perhitungan EMA5, EMA10, EMA20");

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Open", "High", "Low", "Close", "EMA5", "EMA10", "EMA20"
            }
        ));
        jScrollPane1.setViewportView(mainTable);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Perhitungan EMA");
        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jLabel8.setPreferredSize(new java.awt.Dimension(120, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNamaSaham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblKode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblJumlahData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAwalData, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(lblAkhirData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblKode))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblNamaSaham))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lblJumlahData))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(lblAwalData))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(lblAkhirData))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAkhirData;
    private javax.swing.JLabel lblAwalData;
    private javax.swing.JLabel lblCloseHighest;
    private javax.swing.JLabel lblCloseLowest;
    private javax.swing.JLabel lblHighHighest;
    private javax.swing.JLabel lblHighLowest;
    private javax.swing.JLabel lblJumlahData;
    private javax.swing.JLabel lblKode;
    private javax.swing.JLabel lblLowHighest;
    private javax.swing.JLabel lblLowLowest;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblNamaSaham;
    private javax.swing.JLabel lblOpenHighest;
    private javax.swing.JLabel lblOpenLowest;
    private javax.swing.JLabel lblTertinggi;
    private javax.swing.JTable mainTable;
    private javax.swing.JPanel pnlPrice;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean next() {
        return pageAction.next();
    }

    @Override
    public boolean cancel() {
        return pageAction.cancel();
    }

    @Override
    public boolean initialize() {
        try {
            ((EMACounterAction)pageAction).setShare((Share)getWizardAction().getExtra("Share"));
            return pageAction.initialize();
        } catch (Exception ex) {
            Logger.getLogger(EMACounterPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }

    void fillInformation(Share share) {
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        lblKode.setText(share.getKodeSaham());
        lblNamaSaham.setText(share.getNamaSaham());
        lblJumlahData.setText(share.getJumlahData()+" Records");
        lblAwalData.setText(formatter.format(share.getStartDate()));
        lblAkhirData.setText(formatter.format(share.getEndDate()));
        lblOpenHighest.setText(String.format("%.2f",share.getHighestOpen()));
        lblOpenLowest.setText(String.format("%.2f",share.getLowestOpen()));
        lblHighHighest.setText(String.format("%.2f",share.getHighestHigh()));
        lblHighLowest.setText(String.format("%.2f",share.getLowestHigh()));
        lblLowHighest.setText(String.format("%.2f", share.getHighestLow()));
        lblLowLowest.setText(String.format("%.2f", share.getLowestLow()));
        lblCloseHighest.setText(String.format("%.2f", share.getHighestClose()));
        lblCloseLowest.setText(String.format("%.2f", share.getLowestClose()));
    }

}
