/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.mikroskil.elm_skripsi.wizard;

/**
 *
 * @author Andy Wijaya
 */
public abstract class WizardPage extends javax.swing.JPanel {
    
    protected PageAction pageAction;
    private WizardAction wizardAction;
    private String title;
    /**
     * Creates new form WizardPage
     */
    public WizardPage() {
        initComponents();
    }
    
    /**
     * Construct Wizard Action Object
     * @param wizardAction
     * @param title
     */
    public WizardPage(WizardAction wizardAction, String title) {
        this.wizardAction = wizardAction;
        this.title = title;
        initComponents();
    }

    public void setErrorMessage(String errorMessage){
        wizardAction.setErroMessage(errorMessage);
    }
    
    public WizardAction getWizardAction() {
        return wizardAction;
    }

    public void setWizardAction(WizardAction wizardAction) {
        this.wizardAction = wizardAction;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public PageAction getPageAction() {
        return pageAction;
    }

    public void setPageAction(PageAction pageAction) {
        this.pageAction = pageAction;
    }
    
    public abstract boolean next();
    public abstract boolean cancel();
    public abstract boolean initialize();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
